### ISSUE TITLE
[Lib] Add contributors section to README

### ISSUE THREAD

**Issue by brandonroberts** [brandonroberts/angular-routing#23]
I think the all contributors package is commonly used

**Comment by meeroslav** [comment]
If you want to show full avatars then yes. You need to install an `all-contributors` bot.

The other solution is to create open-collective for this project and open-collective provides SVG with mini avatars of contributors (no handles and link to user profile, unfortunately)

**Comment by brandonroberts** [comment]
Added all-contributors to README
