### ISSUE TITLE
[Question] RouteComponentDirective seems obsolete

### ISSUE THREAD

**Issue by meeroslav** [brandonroberts/angular-routing#35]
Based on the code, the sole purpose of `RouteComponentTemplate` is to provide `TemplateRef` for RouteComponent to use as the container outlet. These are equivalent:

* Current custom directive
```html
<route path="/blah">
  <app-something *routeComponent></app-something>
</route>
```
* Any structural directive
```html
<route path="/blah">
  <app-something *ngIf></app-something>
</route>
```
* No directive, just template
```html
<route path="/blah">
  <ng-template>
    <app-something></app-something>
  </ng-template>
</route>
```

Seems unnecessary to define custom directive when `ng-template` within RouteComponent could solve this.

What was the reasoning behind it? Is RouteComponentTemplate planned to have some logic in the future?

**Comment by brandonroberts** [comment]
Yep, they are equivalent, and that's why I added it just so the user doesn't have to remember to wrap every component in an `ng-template` or a unnecessary `ngIf`. I'd like to do something like https://github.com/brandonroberts/angular-routing/issues/37 if possible

**Comment by meeroslav** [comment]
Yup, will look into it. I’ll close this in favor of #37
