### ISSUE TITLE
[Feat] Add ng add support

### ISSUE THREAD

**Issue by brandonroberts** [brandonroberts/angular-routing#9]
- Updates the package.json
- Adds RoutingModule.forRoot() to the AppModule

**Comment by santoshyadavdev** [comment]
I will take it Brandon.

**Comment by santoshyadavdev** [comment]
@brandonroberts is folder structure looks fine to you, Sorry for asking, actually I know plugins create a separate lib for schematics and builder, but here we are creating schematics as part of the library, which I have not done as part of Nx so a little bit confused here.

**Comment by brandonroberts** [comment]
Yea, we'll have to compile the schematics separately, and probably use the @schematics/angular package or another utility library to add the imports for RoutingModule.forRoot() to an NgModule.

**Comment by santoshyadavdev** [comment]
Cool, thanks 😊.
